worlds:
  Winthier:
    Enabled: false
    GenerateHotspots: true
    SpecialBiomes: false
    MiniCaves: false
  Resource:
    Enabled: false
    GenerateHotspots: false
    SpecialBiomes: true
    MiniCaves: false
