worlds:
  Winthier:
    Enabled: true
    GenerateHotspots: true
    SpecialBiomes: false
    Dungeons: false
  Resource:
    Enabled: true
    GenerateHotspots: false
    SpecialBiomes: true
    Dungeons: true
