name: Ore
description: Custom, dynamic ore generation
author: StarTux
version: 0.1
main: com.winthier.ore.OrePlugin
softdepend: [ Exploits, Multiverse-Core ]
commands:
  ore:
    description: Admin interface
    permission: ore.ore
permissions:
  ore.ore:
    description: Use the admin command
    default: op
